version: '3.8'

services:
  postgres:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    container_name: mi_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: